using Microsoft.AspNetCore.Mvc;
using pitchamon.Api.Models;

namespace pitchamon.Api.Controllers;

[ApiController]
[Route("pokemon")]
public class PokemonController : ControllerBase
{
    private static readonly List<Pokemon> PokemonList = 
    [
        //generated by Chat because I'm not doing this by hand
        new Pokemon { Id = 1, Name = "Bulbasaur", Cry = "001.wav" },
        new Pokemon { Id = 2, Name = "Ivysaur", Cry = "002.wav" },
        new Pokemon { Id = 3, Name = "Venusaur", Cry = "003.wav" },
        new Pokemon { Id = 4, Name = "Charmander", Cry = "004.wav" },
        new Pokemon { Id = 5, Name = "Charmeleon", Cry = "005.wav" },
        new Pokemon { Id = 6, Name = "Charizard", Cry = "006.wav" },
        new Pokemon { Id = 7, Name = "Squirtle", Cry = "007.wav" },
        new Pokemon { Id = 8, Name = "Wartortle", Cry = "008.wav" },
        new Pokemon { Id = 9, Name = "Blastoise", Cry = "009.wav" },
        new Pokemon { Id = 10, Name = "Caterpie", Cry = "010.wav" },
        new Pokemon { Id = 11, Name = "Metapod", Cry = "011.wav" },
        new Pokemon { Id = 12, Name = "Butterfree", Cry = "012.wav" },
        new Pokemon { Id = 13, Name = "Weedle", Cry = "013.wav" },
        new Pokemon { Id = 14, Name = "Kakuna", Cry = "014.wav" },
        new Pokemon { Id = 15, Name = "Beedrill", Cry = "015.wav" },
        new Pokemon { Id = 16, Name = "Pidgey", Cry = "016.wav" },
        new Pokemon { Id = 17, Name = "Pidgeotto", Cry = "017.wav" },
        new Pokemon { Id = 18, Name = "Pidgeot", Cry = "018.wav" },
        new Pokemon { Id = 19, Name = "Rattata", Cry = "019.wav" },
        new Pokemon { Id = 20, Name = "Raticate", Cry = "020.wav" },
        new Pokemon { Id = 21, Name = "Spearrow", Cry = "021.wav" },
        new Pokemon { Id = 22, Name = "Fearow", Cry = "022.wav" },
        new Pokemon { Id = 23, Name = "Ekans", Cry = "023.wav" },
        new Pokemon { Id = 24, Name = "Arbok", Cry = "024.wav" },
        new Pokemon { Id = 25, Name = "Pikachu", Cry = "025.wav" },
        new Pokemon { Id = 26, Name = "Raichu", Cry = "026.wav" },
        new Pokemon { Id = 27, Name = "Sandshrew", Cry = "027.wav" },
        new Pokemon { Id = 28, Name = "Sandslash", Cry = "028.wav" },
        new Pokemon { Id = 29, Name = "NidoranF", Cry = "029.wav" },
        new Pokemon { Id = 30, Name = "Nidorina", Cry = "030.wav" },
        new Pokemon { Id = 31, Name = "Nidoqueen", Cry = "031.wav" },
        new Pokemon { Id = 32, Name = "NidoranM", Cry = "032.wav" },
        new Pokemon { Id = 33, Name = "Nidorino", Cry = "033.wav" },
        new Pokemon { Id = 34, Name = "Nidoking", Cry = "034.wav" },
        new Pokemon { Id = 35, Name = "Clefairy", Cry = "035.wav" },
        new Pokemon { Id = 36, Name = "Clefable", Cry = "036.wav" },
        new Pokemon { Id = 37, Name = "Vulpix", Cry = "037.wav" },
        new Pokemon { Id = 38, Name = "Ninetales", Cry = "038.wav" },
        new Pokemon { Id = 39, Name = "Jigglypuff", Cry = "039.wav" },
        new Pokemon { Id = 40, Name = "Wigglytuff", Cry = "040.wav" },
        new Pokemon { Id = 41, Name = "Zubat", Cry = "041.wav" },
        new Pokemon { Id = 42, Name = "Golbat", Cry = "042.wav" },
        new Pokemon { Id = 43, Name = "Oddish", Cry = "043.wav" },
        new Pokemon { Id = 44, Name = "Gloom", Cry = "044.wav" },
        new Pokemon { Id = 45, Name = "Vileplume", Cry = "045.wav" },
        new Pokemon { Id = 46, Name = "Paras", Cry = "046.wav" },
        new Pokemon { Id = 47, Name = "Parasect", Cry = "047.wav" },
        new Pokemon { Id = 48, Name = "Venonat", Cry = "048.wav" },
        new Pokemon { Id = 49, Name = "Venomoth", Cry = "049.wav" },
        new Pokemon { Id = 50, Name = "Diglett", Cry = "050.wav" },
        new Pokemon { Id = 51, Name = "Dugtrio", Cry = "051.wav" },
        new Pokemon { Id = 52, Name = "Meowth", Cry = "052.wav" },
        new Pokemon { Id = 53, Name = "Persian", Cry = "053.wav" },
        new Pokemon { Id = 54, Name = "Psyduck", Cry = "054.wav" },
        new Pokemon { Id = 55, Name = "Golduck", Cry = "055.wav" },
        new Pokemon { Id = 56, Name = "Mankey", Cry = "056.wav" },
        new Pokemon { Id = 57, Name = "Primeape", Cry = "057.wav" },
        new Pokemon { Id = 58, Name = "Growlithe", Cry = "058.wav" },
        new Pokemon { Id = 59, Name = "Arcanine", Cry = "059.wav" },
        new Pokemon { Id = 60, Name = "Poliwag", Cry = "060.wav" },
        new Pokemon { Id = 61, Name = "Poliwhirl", Cry = "061.wav" },
        new Pokemon { Id = 62, Name = "Poliwrath", Cry = "062.wav" },
        new Pokemon { Id = 63, Name = "Abra", Cry = "063.wav" },
        new Pokemon { Id = 64, Name = "Kadabra", Cry = "064.wav" },
        new Pokemon { Id = 65, Name = "Alakazam", Cry = "065.wav" },
        new Pokemon { Id = 66, Name = "Machop", Cry = "066.wav" },
        new Pokemon { Id = 67, Name = "Machoke", Cry = "067.wav" },
        new Pokemon { Id = 68, Name = "Machamp", Cry = "068.wav" },
        new Pokemon { Id = 69, Name = "Bellsprout", Cry = "069.wav" },
        new Pokemon { Id = 70, Name = "Weepinbell", Cry = "070.wav" },
        new Pokemon { Id = 71, Name = "Victreebel", Cry = "071.wav" },
        new Pokemon { Id = 72, Name = "Tentacool", Cry = "072.wav" },
        new Pokemon { Id = 73, Name = "Tentacruel", Cry = "073.wav" },
        new Pokemon { Id = 74, Name = "Geodude", Cry = "074.wav" },
        new Pokemon { Id = 75, Name = "Graveler", Cry = "075.wav" },
        new Pokemon { Id = 76, Name = "Golem", Cry = "076.wav" },
        new Pokemon { Id = 77, Name = "Ponyta", Cry = "077.wav" },
        new Pokemon { Id = 78, Name = "Rapidash", Cry = "078.wav" },
        new Pokemon { Id = 79, Name = "Slowpoke", Cry = "079.wav" },
        new Pokemon { Id = 80, Name = "Slowbro", Cry = "080.wav" },
        new Pokemon { Id = 81, Name = "Magnemite", Cry = "081.wav" },
        new Pokemon { Id = 82, Name = "Magneton", Cry = "082.wav" },
        new Pokemon { Id = 83, Name = "Farfetchd", Cry = "083.wav" },
        new Pokemon { Id = 84, Name = "Doduo", Cry = "084.wav" },
        new Pokemon { Id = 85, Name = "Dodrio", Cry = "085.wav" },
        new Pokemon { Id = 86, Name = "Seel", Cry = "086.wav" },
        new Pokemon { Id = 87, Name = "Dewgong", Cry = "087.wav" },
        new Pokemon { Id = 88, Name = "Grimer", Cry = "088.wav" },
        new Pokemon { Id = 89, Name = "Muk", Cry = "089.wav" },
        new Pokemon { Id = 90, Name = "Shellder", Cry = "090.wav" },
        new Pokemon { Id = 91, Name = "Cloyster", Cry = "091.wav" },
        new Pokemon { Id = 92, Name = "Gastly", Cry = "092.wav" },
        new Pokemon { Id = 93, Name = "Haunter", Cry = "093.wav" },
        new Pokemon { Id = 94, Name = "Gengar", Cry = "094.wav" },
        new Pokemon { Id = 95, Name = "Onix", Cry = "095.wav" },
        new Pokemon { Id = 96, Name = "Drowzee", Cry = "096.wav" },
        new Pokemon { Id = 97, Name = "Hypno", Cry = "097.wav" },
        new Pokemon { Id = 98, Name = "Krabby", Cry = "098.wav" },
        new Pokemon { Id = 99, Name = "Kingler", Cry = "099.wav" },
        new Pokemon { Id = 100, Name = "Voltorb", Cry = "100.wav" },
        new Pokemon { Id = 101, Name = "Electrode", Cry = "101.wav" },
        new Pokemon { Id = 102, Name = "Exeggcute", Cry = "102.wav" },
        new Pokemon { Id = 103, Name = "Exeggutor", Cry = "103.wav" },
        new Pokemon { Id = 104, Name = "Cubone", Cry = "104.wav" },
        new Pokemon { Id = 105, Name = "Marowak", Cry = "105.wav" },
        new Pokemon { Id = 106, Name = "Hitmonlee", Cry = "106.wav" },
        new Pokemon { Id = 107, Name = "Hitmonchan", Cry = "107.wav" },
        new Pokemon { Id = 108, Name = "Lickitung", Cry = "108.wav" },
        new Pokemon { Id = 109, Name = "Koffing", Cry = "109.wav" },
        new Pokemon { Id = 110, Name = "Weezing", Cry = "110.wav" },
        new Pokemon { Id = 111, Name = "Rhyhorn", Cry = "111.wav" },
        new Pokemon { Id = 112, Name = "Rhydon", Cry = "112.wav" },
        new Pokemon { Id = 113, Name = "Chansey", Cry = "113.wav" },
        new Pokemon { Id = 114, Name = "Tangela", Cry = "114.wav" },
        new Pokemon { Id = 115, Name = "Kangaskhan", Cry = "115.wav" },
        new Pokemon { Id = 116, Name = "Horsea", Cry = "116.wav" },
        new Pokemon { Id = 117, Name = "Seadra", Cry = "117.wav" },
        new Pokemon { Id = 118, Name = "Goldeen", Cry = "118.wav" },
        new Pokemon { Id = 119, Name = "Seaking", Cry = "119.wav" },
        new Pokemon { Id = 120, Name = "Staryu", Cry = "120.wav" },
        new Pokemon { Id = 121, Name = "Starmie", Cry = "121.wav" },
        new Pokemon { Id = 122, Name = "MrMime", Cry = "122.wav" },
        new Pokemon { Id = 123, Name = "Scyther", Cry = "123.wav" },
        new Pokemon { Id = 124, Name = "Jynx", Cry = "124.wav" },
        new Pokemon { Id = 125, Name = "Electabuzz", Cry = "125.wav" },
        new Pokemon { Id = 126, Name = "Magmar", Cry = "126.wav" },
        new Pokemon { Id = 127, Name = "Pinsir", Cry = "127.wav" },
        new Pokemon { Id = 128, Name = "Tauros", Cry = "128.wav" },
        new Pokemon { Id = 129, Name = "Magikarp", Cry = "129.wav" },
        new Pokemon { Id = 130, Name = "Gyarados", Cry = "130.wav" },
        new Pokemon { Id = 131, Name = "Lapras", Cry = "131.wav" },
        new Pokemon { Id = 132, Name = "Ditto", Cry = "132.wav" },
        new Pokemon { Id = 133, Name = "Eevee", Cry = "133.wav" },
        new Pokemon { Id = 134, Name = "Vaporeon", Cry = "134.wav" },
        new Pokemon { Id = 135, Name = "Jolteon", Cry = "135.wav" },
        new Pokemon { Id = 136, Name = "Flareon", Cry = "136.wav" },
        new Pokemon { Id = 137, Name = "Porygon", Cry = "137.wav" },
        new Pokemon { Id = 138, Name = "Omanyte", Cry = "138.wav" },
        new Pokemon { Id = 139, Name = "Omastar", Cry = "139.wav" },
        new Pokemon { Id = 140, Name = "Kabuto", Cry = "140.wav" },
        new Pokemon { Id = 141, Name = "Kabutops", Cry = "141.wav" },
        new Pokemon { Id = 142, Name = "Aerodactyl", Cry = "142.wav" },
        new Pokemon { Id = 143, Name = "Snorlax", Cry = "143.wav" },
        new Pokemon { Id = 144, Name = "Articuno", Cry = "144.wav" },
        new Pokemon { Id = 145, Name = "Zapdos", Cry = "145.wav" },
        new Pokemon { Id = 146, Name = "Moltres", Cry = "146.wav" },
        new Pokemon { Id = 147, Name = "Dratini", Cry = "147.wav" },
        new Pokemon { Id = 148, Name = "Dragonair", Cry = "148.wav" },
        new Pokemon { Id = 149, Name = "Dragonite", Cry = "149.wav" },
        new Pokemon { Id = 150, Name = "Mewtwo", Cry = "150.wav" },
        new Pokemon { Id = 151, Name = "Mew", Cry = "151.wav" } 
    ];

    [HttpGet]
    public ActionResult<object> GetAllPokemon()
    {
        return Ok(new { pokemon = PokemonList });
    }

    [HttpGet("{name}")]
    public ActionResult<Pokemon> GetPokemonByName(string name)
    {
        var pokemon = PokemonList.FirstOrDefault(p =>
            p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

        if (pokemon == null)
        {
            return NotFound(new { error = "Pokémon not found" });
        }

        return Ok(pokemon);
    }

    [HttpPost]
    public ActionResult<object> CreatePokemon([FromBody] CreatePokemonRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Name) || string.IsNullOrWhiteSpace(request.Cry))
        {
            return BadRequest(new { error = "Missing required fields" });
        }

        var exists = PokemonList.Any(p =>
            p.Name.Equals(request.Name, StringComparison.OrdinalIgnoreCase));

        if (exists)
        {
            return Conflict(new { error = "Pokémon already exists" });
        }

        var nextId = PokemonList.Count == 0 ? 1 : PokemonList.Max(p => p.Id) + 1;

        var pokemon = new Pokemon
        {
            Id = nextId,
            Name = request.Name,
            Cry = request.Cry
        };

        PokemonList.Add(pokemon);

        return CreatedAtAction(
            nameof(GetPokemonByName),
            new { name = pokemon.Name },
            new
            {
                message = "Pokémon added successfully",
                pokemon
            });
    }
}