on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v6

      - name: Set Up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
          
      - name: Confirm Workflow is Running
        run: echo "Workflow is running successfully!"

#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build
#        run: dotnet build --no-restore --configuration Release
#
#      - name: Run Tests
#        run: dotnet test --no-build --configuration Release